#!/usr/bin/env bash

set -eu

install() {

  local packages pyrelease runtime

  runtime=$PWD/runtime
  pyrelease=3.12

  # Install uv.

  curl -LsSf https://astral.sh/uv/0.9.13/install.sh | env UV_UNMANAGED_INSTALL=$runtime/bin sh

  # Install Python via uv.

  $runtime/bin/uv python install $pyrelease --install-dir $runtime/opt --no-bin --no-cache

  # Create, activate, and update virtual environment.

  $(find $runtime/opt -type f -name python$pyrelease) -m venv $runtime/env
  source $runtime/env/bin/activate
  export XDG_CACHE_HOME=$runtime/var/cache
  python -m pip install pip --upgrade

  # Install core packages.

  packages=(
    #   'earthkit-data<0.14.0'
    #   'numpy<2.3'
    #   mpi4py
    #   trimesh
    anemoi-datasets==0.5.*
    anemoi-graphs==0.6.*
    anemoi-inference==0.6.*
    anemoi-models==0.8.*
    anemoi-training==0.5.*
    ufs2arco==0.17.*
  )
  python -m pip install ${packages[@]}

  # Install uwtools from git.

  python -m pip install "git+https://github.com/ufs-community/uwtools@v2.12.0#subdirectory=src"

  # Install flash-attention:

  # module load cuda/12.8.1
  # python -m pip install flash-attn --no-build-isolation
}

install
