#!/usr/bin/env bash

set -eu

fail() { echo $1 && exit 1; }

install() {

  local cudamod packages pyrelease runtime

  cudamod=$(module --terse spider cuda | sort -n | tail -n1)
  test -z "${codamod:-}" && fail "Found no CUDA module to load"
  pyrelease=3.12
  runtime=$PWD/runtime

  # Install uv.

  curl -LsSf https://astral.sh/uv/0.9.13/install.sh | env UV_UNMANAGED_INSTALL=$runtime/bin sh

  # Install Python via uv.

  $runtime/bin/uv python install $pyrelease --install-dir $runtime/opt --no-bin --no-cache

  # Create, activate, and update virtual environment.

  $(find $runtime/opt -type f -name python$pyrelease) -m venv $runtime/env
  source $runtime/env/bin/activate
  export XDG_CACHE_HOME=$runtime/var/cache
  python -m pip install pip --upgrade

  # Install core packages.

  packages=(
    anemoi-datasets==0.5.*
    anemoi-graphs==0.6.*
    anemoi-inference==0.6.*
    anemoi-models==0.8.*
    anemoi-training==0.5.*
    ufs2arco==0.17.*
  )
  python -m pip install ${packages[@]}

  # Install uwtools from git.

  python -m pip install "git+https://github.com/ufs-community/uwtools@v2.12.0#subdirectory=src"

  # Install flash-attention:

  echo Loading $cudamod
  python -m pip install flash-attn --no-build-isolation
}

install
